✨角色生日查询/推送
PaiGramTeam/PaiGram pull request #190
Opened 2022-10-18 05:44 UTC by zhxycn

## 描述 / Description

```
角色生日查询/推送
```

## 更改检查表 / Change Checklist
  
- [ ] 有插件命令更新
  - [ ] 已更新 bot 帮助文件
- [ ] 有流程交互
  - [ ] 指引明确
  - [ ] 可以退出
- [ ] 会触发频率限制
  - [ ] 有对应的限制措施
- [ ] 需要用户输入数据
  - [ ] 验证用户数据
  - [ ] 如果是文件，检查了文件大小
  - [ ] 对保存的数据再次进行了验证
- [ ] 添加了新的依赖包
- [ ] 测试
  - [ ] 本地通过了测试
  - [ ] CI 通过了测试

## 说明 / Note
Todo:
- [x] 查询今日角色生日列表
- [ ] 查询任意角色的生日信息
- [ ] 自动推送

2022-10-18 07:13 UTC, luoshuijs commented
为啥不能获取最近一个月的

2022-10-29 15:37 UTC, zhxycn commented
自动推送放到4.0重构后吧，先这样了

2022-10-29 15:55 UTC, luoshuijs commented
所以说能合并了就把tag拿下啊 @zhxycn

2022-10-29 15:58 UTC, luoshuijs requested changes

2022-10-29 15:58 UTC, luoshuijs commented on plugins/genshin/birthday.py
> +            reply_message = await update.effective_message.reply_text(text)
这里为啥不用  `reply_message = await message.reply_text(text)`

2022-10-29 15:58 UTC, luoshuijs commented on plugins/genshin/birthday.py
> +        message = update.effective_message
你这都是摆设变量了

2022-10-29 16:02 UTC, luoshuijs commented
还有就是每次获取 `update.effective_message` 会进行一次 `message` 寻找，会提高运行时间。

2022-10-29 16:56 UTC, luoshuijs approved these changes

2022-10-29 17:00 UTC, merged