✨ 添加错误平台
PaiGramTeam/PaiGram pull request #191
Opened 2022-10-18 08:44 UTC by omg-xtao

## 该 PR 相关 Issue / Involved issue

Close #

## 描述 / Description

```
添加错误平台
```

## 更改检查表 / Change Checklist
  
- [ ] 有插件命令更新
  - [ ] 已更新 bot 帮助文件
- [ ] 有流程交互
  - [ ] 指引明确
  - [ ] 可以退出
- [ ] 会触发频率限制
  - [ ] 有对应的限制措施
- [ ] 需要用户输入数据
  - [ ] 验证用户数据
  - [ ] 如果是文件，检查了文件大小
  - [ ] 对保存的数据再次进行了验证
- [x] 添加了新的依赖包
- [x] 测试
  - [x] 本地通过了测试
  - [ ] CI 通过了测试

## 说明 / Note

2022-10-18 08:57 UTC, karakoo commented on utils/log/_handler.py
> -        path.parent.mkdir(exist_ok=True)
这整个 `wile True` 循环可以删了

2022-10-18 09:03 UTC, luoshuijs commented on modules/error/sentry.py
> +sentry_sdk_git_hash = run("git rev-parse HEAD", stdout=PIPE, shell=True).stdout.decode().strip()
https://security.openstack.org/guidelines/dg_use-subprocess-securely.html

2022-10-18 09:03 UTC, luoshuijs commented on modules/error/sentry.py
> +sentry_sdk_git_hash = run("git rev-parse HEAD", stdout=PIPE, shell=True).stdout.decode().strip()
https://security.openstack.org/guidelines/dg_use-subprocess-securely.html

2022-10-18 09:06 UTC, luoshuijs requested changes

2022-10-18 09:06 UTC, luoshuijs commented on plugins/system/log.py
> +            pb_url = await self.send_to_pb(error_log)
因为是可选配置，需要判断是否需要上传日记，并且在没配置的情况下默认关闭

2022-10-18 09:11 UTC, luoshuijs commented
有个问题  要不要动 这个地方
https://github.com/luoshuijs/TGPaimonBot/blob/aafcb424a9894bade3d7637e46cd673b23bcef3b/plugins/system/errorhandler.py#L27-L28

2022-10-18 09:15 UTC, omg-xtao commented on plugins/system/log.py
> +            pb_url = await self.send_to_pb(error_log)
create_pb 函数已经默认返回空

2022-10-19 12:20 UTC, luoshuijs approved these changes

2022-10-19 12:22 UTC, merged