feat: 增加 html to image 的缓存
PaiGramTeam/PaiGram pull request #192
Opened 2022-10-18 10:52 UTC by chuangbo

问题

用户短时间内发送多条重复命令，返回的图片未发生改变。在这样的情况下，希望派蒙可以提高回复速度。

方案

* 增加 html to image 缓存
* 对 template_service.render 进行封装，管理缓存逻辑
* cache key 为 html 的 sha256
* cache value 为 reply_photo 后 telegram 返回的 file_id
* 存入 redis，并设置合理的 ttl

## 该 PR 相关 Issue / Involved issue

Close #189

## 描述 / Description

```
见 #189 讨论
```

## 更改检查表 / Change Checklist
  
- [ ] 有插件命令更新
  - [ ] 已更新 bot 帮助文件
- [ ] 有流程交互
  - [ ] 指引明确
  - [ ] 可以退出
- [ ] 会触发频率限制
  - [ ] 有对应的限制措施
- [ ] 需要用户输入数据
  - [ ] 验证用户数据
  - [ ] 如果是文件，检查了文件大小
  - [ ] 对保存的数据再次进行了验证
- [ ] 添加了新的依赖包
- [ ] 测试
  - [ ] 本地通过了测试
  - [ ] CI 通过了测试

## 说明 / Note

2022-10-18 11:41 UTC, luoshuijs commented on core/template/cache.py
> +    async def set_data(self, html: str, file_id: str, ttl: int = 60 * 60):
我觉得默认 `TTL` 1小时太短了吧，至少是大于一周甚至一个月，因为有些数据根本真的1个月都不会发生变化，比如说角色列表

2022-10-18 11:41 UTC, luoshuijs commented on core/template/services.py
> +class RenderResult:
还有个 `reply_document` 需要添加

2022-10-18 11:49 UTC, luoshuijs requested changes

2022-10-18 11:49 UTC, luoshuijs commented on core/template/services.py
> +    async def reply_photo(self, message: Message, *args, **kwargs):
给 `reply_photo` 添加 `ttl` 可选参数，包括后面的

2022-10-18 11:50 UTC, luoshuijs commented on core/template/cache.py
> +    async def set_data(self, html: str, file_id: str, ttl: int = 60 * 60):
~~有的人已经非到几个版本角色列表动都不动了，还有屯屯鼠的那种~~

2022-10-18 12:01 UTC, luoshuijs commented
检查单：需要对于修改的插件
- [ ]  help
- [ ]  abyss
- [ ]  abyss_team
- [ ]  avatar_list
- [ ] ~~daily_noto~~ 
- [ ]  ~~gacha~~
- [ ]  gacha_count
- [ ]  gacha_log
- [ ]  ledger
- [ ]  player_card
- [ ]  stsats
- [ ]  weapon

划线部分是因为不适于利用文件缓存提升传输速度

2022-10-18 15:52 UTC, luoshuijs commented
颅内DEBUG检查单：
- [ ] `reply_photo `返回的 `file_id ` 和 `reply_document` 返回的 `file_id ` 必须分开，不能在Redis混用

2022-10-22 06:16 UTC, luoshuijs commented
新检查单

- [ ] `daily_material ` 插件需要在HTML修改当前时间，改为 `月-日 星期几` 即可，不然会极大降低缓存命中

2022-10-22 06:22 UTC, luoshuijs approved these changes

2022-10-22 06:57 UTC, omg-xtao approved these changes

2022-10-22 07:03 UTC, merged