:sparkles: Try using `SIMNet`
PaiGramTeam/PaiGram pull request #570
Opened 2023-06-12 00:49 UTC by luoshuijs

2023-06-13 08:31 UTC, omg-xtao approved these changes

2023-06-13 08:36 UTC, omg-xtao requested changes
仍有 genshin 依赖残留

2023-06-28 13:43 UTC, luoshuijs commented
残留已经清理
以下目录合并前再清理
`utils/genshin.py`
`utils/patch/genshin.py`

2023-07-02 05:56 UTC, omg-xtao approved these changes

2023-07-18 09:29 UTC, merged