支持资源点查询
PaiGramTeam/PaiGram pull request #68
Opened 2022-07-10 08:46 UTC by zhxycn

首次使用需要从米游社下载部分资源，故首次运行响应时间较长，具体时长取决于服务器网速和与米游社的连接质量。

命令|功能
-|-
/map [资源名称]|查询资源点
/map list|资源列表

>图片长/宽大于2048像素时转为文件格式发送

2022-07-10 10:09 UTC, zhxycn commented
能用就行（

2022-07-10 11:03 UTC, luoshuijs requested changes
哼哼哼啊啊啊啊啊啊啊啊

2022-07-10 11:03 UTC, luoshuijs commented on plugins/map.py
> +            return await inquire_resource_list(message)
无需返回 `Message`

2022-07-10 11:03 UTC, luoshuijs commented on plugins/map.py
> +            await message.reply_document(open(f"temp{sep}map.jpg", mode='rb+'), caption=text)
本项目缓存文件夹为 `cache`

2022-07-10 11:03 UTC, luoshuijs commented on service/map.py
> +            and exists(f"""{os.path.dirname(__file__), os.path.pardir, "resources", os.sep}data{os.sep}list.json""")
未将下载的资源数据文件加入 `.gitignore` 排除列表
考虑到作为外置资源文件，方便本地资源文件管理，应该放在 `cache`

2022-07-10 11:03 UTC, luoshuijs commented on plugins/map.py
> +init_resource_map = False
有 `class` 能方便 `init` 为啥不考虑放？.jpg

2022-07-10 11:03 UTC, luoshuijs commented on plugins/map.py
> +async def inquire_resource_list(message):
冷知识，有个东西叫 `@staticmethod`

2022-07-10 11:13 UTC, luoshuijs requested changes

2022-07-10 11:13 UTC, luoshuijs commented on plugins/map.py
> +    @restricts()
我看了一下渲染需要的内存，我怂了
建议 `@restricts` 限制调用冷却时间为20秒

2022-07-10 14:49 UTC, luoshuijs commented
草，注释也不全好烦.jpg

2022-07-10 16:31 UTC, luoshuijs commented
代码我只敢保证 能加载成功 睡觉.jpg

2022-07-11 01:04 UTC, zhxycn commented
<del>本来也不是不能用（</del>

2022-07-19 07:47 UTC, luoshuijs requested changes
颅内测试通过了 我不好说
草 我还按错了

2022-07-20 13:17 UTC, zhxycn commented
![](https://user-images.githubusercontent.com/99539499/174416459-b6e5bfbb-63e4-4767-b6ac-76e7a4369978.png)

2022-07-22 10:03 UTC, luoshuijs commented
@zhxycn 渲染出的图片有黑屏，目前无法解决，至于怎么黑屏去看群里吧

2022-07-22 10:17 UTC, zhxycn commented
修改后代码未测试，初版提交无法复现此问题

2022-07-22 10:19 UTC, luoshuijs commented
@zhxycn 因为PR有点久远了，现在你测试初版是真没有这个问题嘛

2022-07-22 10:20 UTC, luoshuijs commented
你尝试复制一个分支把代码撤回到初始版本，看看是否有问题

2022-07-22 10:41 UTC, omg-xtao approved these changes

2022-07-22 10:43 UTC, luoshuijs approved these changes

2022-07-22 12:39 UTC, merged