:recycle: refactor `/daily_material`
PaiGramTeam/PaiGram pull request #686
Opened 2023-11-03 20:53 UTC by xr1s

## 该 PR 相关 Issue / Involved issue

## 描述 / Description

重构 `/daily_material`，主要重构内容
1. `DailyMaterial.data` 采用新的格式存储，并重命名为 `DailyMaterial.everyday_materials`。新的结构使用周几作为第一个索引，这样每次请求 `/daily_material` 不再需要构造 `local_data`，可以直接使用 `everyday_materials[weekday]` 获取所有信息。
2. 简单包装了一下 `GenshinClient`，在出现没有必要继续请求的情况下（Cookie 失效或未启用养成计算器）设置状态为 damaged 并阻止进一步请求。这里感觉可以继续使用 `__enter__` 和 `__exit__` Context Manager 解耦异常处理逻辑进行代码优化，这个留到下次再看看。
3. `_get_data_from_user` 返回用户拥有的物品数据结构改为了 Item ID 索引的 Item Dict，更容易通过 ID 判断用户是否拥有该角色、武器。此前是 `List[ItemData]`，判断是否拥有某个 Item 是通过一次扫描获取的，平添运行和理解复杂度。
4. 特意提取并区分开了构造角色和武器的区域信息逻辑 `area_user_avatar` 和 `area_user_weapon`，降低主逻辑的复杂度。
5. 重构并提取了解析 honey impact 首页源码的逻辑。~~最近发现 Ambr Project 的接口好像更好用，见异思迁了。~~

一些小优化：
1. 在修改过的逻辑中尽可能去除了 Language Server 对类型标注的报错。
2. 增加了一些方法和变量的注释。

## 更改检查表 / Change Checklist
  
- [ ] 有插件命令更新
  - [ ] 已更新 bot 帮助文件
- [ ] 有流程交互
  - [ ] 指引明确
  - [ ] 可以退出
- [ ] 会触发频率限制
  - [ ] 有对应的限制措施
- [ ] 需要用户输入数据
  - [ ] 验证用户数据
  - [ ] 如果是文件，检查了文件大小
  - [ ] 对保存的数据再次进行了验证
- [ ] 添加了新的依赖包
- [ ] 测试
  - [ ] 本地通过了测试
  - [ ] CI 通过了测试

## 说明 / Note

2023-11-03 21:49 UTC, xr1s commented
关于 CI 中提及的 lxml 安全性问题，CI 推荐的 defusedxml 库认为 lxml 已经安全并废弃了自己的 lxml 包：
https://github.com/tiran/defusedxml#defusedxmllxml

2023-11-04 03:02 UTC, luoshuijs requested changes

2023-11-04 03:02 UTC, luoshuijs commented on plugins/genshin/daily/material.py
> +import typing
这里出现了两个 `typing` 导入

2023-11-04 03:02 UTC, luoshuijs commented on plugins/genshin/daily/material.py
> +import os.path
推荐使用 `from os import path`，这样可以直接使用 path 而不必再次引用 os。

before
```python
import os.path

if os.path.exists("myfile.txt"):
    print("The file exists.")
```

after
```python
from os import path

if path.exists("myfile.txt"):
    print("The file exists.")
```

2023-11-04 03:02 UTC, luoshuijs commented on plugins/genshin/daily/material.py
> -from bs4 import BeautifulSoup
话说不用 `Beautiful Soup` 而是用 `cssselect` 是有什么说法.jpg

2023-11-04 03:32 UTC, luoshuijs commented on plugins/genshin/daily/material.py
> +            href = typing.cast(str, element.attrib["href"])  # Item ID 在 href 中
推荐使用 `href: str = element.attrib["href"]` 直接告诉检查器这个一定是个 `str`
代码更简洁

2023-11-04 03:32 UTC, luoshuijs commented on plugins/genshin/daily/material.py
> +    honey_item_url_map: Dict[str, str] = {
我有个问题，你那边是啥编辑器检查这么严格.jpg

2023-11-04 03:36 UTC, luoshuijs commented on plugins/genshin/daily/material.py
> -from bs4 import BeautifulSoup
https://github.com/PaiGramTeam/PaiGram/pull/686#issuecomment-1793143244
~~有一说一，用 bs4 就没有这个问题~~

2023-11-04 04:02 UTC, luoshuijs commented on plugins/genshin/daily/material.py
> -from bs4 import BeautifulSoup
## `bs4+lxml` vs `cssselect+lxml`

### 初始化 + CSS选择器

```python
calendar = lxml.etree.HTML(source).cssselect(".calendar_day_wrap")[0]
```

```python
soup = BeautifulSoup(source, 'lxml')
calendar = soup.select_one(".calendar_day_wrap")
```

### 查找元素

```python
for div in element.iterfind("div")
```

```python
for div in element.find_all("div")
```

2023-11-04 04:04 UTC, Billyzou0741326 commented on plugins/genshin/daily/material.py
> +                ascendible_items = everyday_materials[weekday][current_country]
`ascendible` -> `ascendable`

2023-11-04 04:16 UTC, Billyzou0741326 approved these changes
Works fine in local

2023-11-04 06:41 UTC, luoshuijs commented on plugins/genshin/daily/material.py
> +            self.everyday_materials = _parse_honey_impact_source(response.content)
我在想这里 `response.text` 是不是好一些

2023-11-04 06:49 UTC, luoshuijs reviewed
不过我在想要不要写个叫 `EverydayMaterials`  的类，里面有个 `get/set` 方法，传入参数就是地区/当前周几，毕竟个人感觉这个数据结构其实不直观

2023-11-04 06:49 UTC, luoshuijs commented on plugins/genshin/daily/material.py
> +    everyday_materials: List[Dict[str, "AreaDailyMaterials"]] = None  # type: ignore
```suggestion
    everyday_materials: Optional[List[Dict[str, "AreaDailyMaterials"]]] = None
```

2023-11-04 12:19 UTC, xr1s commented on plugins/genshin/daily/material.py
> +            href = typing.cast(str, element.attrib["href"])  # Item ID 在 href 中
我这里 pyright 还是报错。要不后面加个 `type: ignore` 压制报错。
```
Expression of type "str | list[str]" cannot be assigned to declared type "str"
  Type "str | list[str]" cannot be assigned to type "str"
    "list[str]" is incompatible with "str" (Pyright reportGeneralTypeIssues)
```

2023-11-04 17:41 UTC, xr1s commented on plugins/genshin/daily/material.py
> +import typing
这里主要是因为我需要用到 `typing.cast`
我认为单独的 `cast` 误导性比较强，用 `typing.cast` 会比较清晰。

2023-11-05 02:33 UTC, luoshuijs commented on plugins/genshin/daily/material.py
> +            href = typing.cast(str, element.attrib["href"])  # Item ID 在 href 中
真严格啊这个类型检查****

2023-11-05 10:52 UTC, xr1s commented on plugins/genshin/daily/material.py
> +            self.everyday_materials = _parse_honey_impact_source(response.content)
这是出于什么考虑？

2023-11-05 10:52 UTC, xr1s commented on plugins/genshin/daily/material.py
> +                ascendible_items = everyday_materials[weekday][current_country]
Fixed，其实两个单词都可以

2023-11-05 10:53 UTC, xr1s commented on plugins/genshin/daily/material.py
> +            href = typing.cast(str, element.attrib["href"])  # Item ID 在 href 中
那我先 resolve 了？

2023-11-05 10:55 UTC, xr1s commented on plugins/genshin/daily/material.py
> +    everyday_materials: List[Dict[str, "AreaDailyMaterials"]] = None  # type: ignore
改成了 `[{} for _ in range(7)]`，不想改成 `Optional` 是因为会有很多 pyright 类型提示...

2023-11-05 11:04 UTC, xr1s commented
> 不过我在想要不要写个叫 `EverydayMaterials` 的类，里面有个 `get/set` 方法，传入参数就是地区/当前周几，毕竟个人感觉这个数据结构其实不直观

这个真的可以有，下次改还是现在就改。

2023-11-08 07:43 UTC, luoshuijs commented
@xr1s 最好一起改吧

2023-11-22 11:22 UTC, xr1s commented
@luoshuijs Data 类加好了
注意到还有个小问题，现在 `DATA_FILE_PATH` 是用 `PROJECT_ROOT` 拼接的，在这个 PR 提出之后加上了 `CACHE_DIR` / `DATA_DIR` 和 `METADATA_DIR`，我想顺便把这个一起改掉吧。
到底

2023-11-22 12:18 UTC, luoshuijs approved these changes

2023-11-22 12:19 UTC, luoshuijs commented
我看了应该没什么问题了，搞完最后更改就可以合并了

2023-11-22 13:36 UTC, merged

2023-11-22 13:47 UTC, luoshuijs commented
close #253